FROM golang:1.24-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
COPY cmd ./cmd
COPY internal ./internal

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/worker ./cmd/worker

FROM alpine:3.20

WORKDIR /app
RUN apk add --no-cache ffmpeg ca-certificates
COPY --from=builder /out/worker /app/worker

ENTRYPOINT ["/app/worker"]
